services:
  # api:
  #   container_name: gqlapp.com
  #   build:
  #     context: .
  #     dockerfile: ./api/Dockerfile
  #   env_file:
  #     - .env.local
  #   depends_on:
  #     - database
  #   ports:
  #     - "8081:8081"
  #   restart: on-failure

  database:
    image: postgres:latest
    container_name: gqlapp-db
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # - ./database/testdata/test_tasks.sql:/docker-entrypoint-initdb.d/test_tasks.sql
      # - ./database/testdata/test_companies.sql:/docker-entrypoint-initdb.d/test_companies.sql
      # - ./database/testdata/test_hearings.sql:/docker-entrypoint-initdb.d/test_hearings.sql
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kikumemodb
    restart: always

  gateway:
    image: hasura/graphql-engine:v2.31.0
    container_name: gqlapp-gateway
    ports:
      - 9090:8080
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@database:5432/kikumemodb
      PG_DATABASE_URL: postgres://postgres:postgres@database:5432/kikumemodb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true" ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_ADMIN_SECRET: hasuraadmin
      HASURA_GRAPHQL_AKUAS_BACKEND_REMOTE_SCHEMA_URL: http://api:9001/graphql
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
      # HASURA_GRAPHQL_JWT_SECRET: >
      #   {
      #     "type":"RS256",
      #     "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
      #     "audience": "dev-kikumemo",
      #     "issuer": "https://securetoken.google.com/dev-kikumemo"
      #   }
    restart: always
    depends_on:
      - database
