openapi: "3.0.0"
info:
  version: 1.0.0
  title: Microblog
  description: API for mycroblog
  contact:
    name: rinoguchi
    email: xxx@xxx.com
    url: https://rinoguchi.net
  license:
    name: MIT
    url: https://opensource.org/licenses/mit-license.php
servers:
  - url: http://localhost:9090
paths:
  /playground:
    get:
      description: get playground
      operationId: getPlayground
      responses:
        "200":
          description: playground response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Playground"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /graphql:
    post:
      tags:
        - etc
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: GraphQL query
                variables:
                  type: object
                  description: Variables for the query (if any)
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: Query result
                  errors:
                    type: array
                    items:
                      type: object
                      description: GraphQL errors (if any)
  /companies:
    post:
      description: create a new company
      operationId: addCompany
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewCompany"
      responses:
        "200":
          description: company response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      description: get companies
      operationId: getCompanies
      responses:
        "200":
          description: comment response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Playground:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          maxLength: 100
    CommonProperties:
      type: object
      properties:
        id:
          type: string
          format: byte
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewCompany:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 100
        representative_name:
          type: string
          maxLength: 100
        status:
          type: string
          maxLength: 100
        icon_img_url:
          type: string
          maxLength: 100

    Company:
      allOf:
        - $ref: "#/components/schemas/NewCompany"
        - $ref: "#/components/schemas/CommonProperties"

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
