package: handler
additional-imports:
  - package: github.com/younghan-jo/gqlgen-todos/api/models
    alias: .
generate:
  echo-server: true
  strict-server: true
  embedded-spec: true
output: ../handler/handler.gen.go
