// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	BusinessCategoryMasters                string
	Companies                              string
	HearingProjectMembers                  string
	HearingProjects                        string
	Hearings                               string
	IndustryMasters                        string
	PaymentHistories                       string
	PaymentUsers                           string
	ProjectSpecificSolutions               string
	SolutionComplaintHandlingProducts      string
	SolutionConstructionManagementProducts string
	SolutionCostControlProducts            string
	SolutionKpiManagementProducts          string
	SolutionMasters                        string
	SolutionOcrProducts                    string
	SolutionPackagingProducts              string
	SolutionProducts                       string
	SolutionSaasManagementProducts         string
	SolutionSaasResearchProducts           string
	SolutionWMSProducts                    string
	TaskEfficiency                         string
	TaskMemos                              string
	TaskProcess                            string
	Tasks                                  string
	TicketHistories                        string
	Tickets                                string
	Users                                  string
}{
	BusinessCategoryMasters:                "business_category_masters",
	Companies:                              "companies",
	HearingProjectMembers:                  "hearing_project_members",
	HearingProjects:                        "hearing_projects",
	Hearings:                               "hearings",
	IndustryMasters:                        "industry_masters",
	PaymentHistories:                       "payment_histories",
	PaymentUsers:                           "payment_users",
	ProjectSpecificSolutions:               "project_specific_solutions",
	SolutionComplaintHandlingProducts:      "solution_complaint_handling_products",
	SolutionConstructionManagementProducts: "solution_construction_management_products",
	SolutionCostControlProducts:            "solution_cost_control_products",
	SolutionKpiManagementProducts:          "solution_kpi_management_products",
	SolutionMasters:                        "solution_masters",
	SolutionOcrProducts:                    "solution_ocr_products",
	SolutionPackagingProducts:              "solution_packaging_products",
	SolutionProducts:                       "solution_products",
	SolutionSaasManagementProducts:         "solution_saas_management_products",
	SolutionSaasResearchProducts:           "solution_saas_research_products",
	SolutionWMSProducts:                    "solution_wms_products",
	TaskEfficiency:                         "task_efficiency",
	TaskMemos:                              "task_memos",
	TaskProcess:                            "task_process",
	Tasks:                                  "tasks",
	TicketHistories:                        "ticket_histories",
	Tickets:                                "tickets",
	Users:                                  "users",
}
