// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// SolutionKpiManagementProduct is an object representing the database table.
type SolutionKpiManagementProduct struct { // KPI管理プロダクトID
	ID []byte `boil:"id" json:"id" toml:"id" yaml:"id"`
	// ソリューションプロダクトID
	SolutionProductID []byte `boil:"solution_product_id" json:"solution_product_id" toml:"solution_product_id" yaml:"solution_product_id"`
	// データ作成日
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// データ更新日
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *solutionKpiManagementProductR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L solutionKpiManagementProductL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SolutionKpiManagementProductColumns = struct {
	ID                string
	SolutionProductID string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "id",
	SolutionProductID: "solution_product_id",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

var SolutionKpiManagementProductTableColumns = struct {
	ID                string
	SolutionProductID string
	CreatedAt         string
	UpdatedAt         string
}{
	ID:                "solution_kpi_management_products.id",
	SolutionProductID: "solution_kpi_management_products.solution_product_id",
	CreatedAt:         "solution_kpi_management_products.created_at",
	UpdatedAt:         "solution_kpi_management_products.updated_at",
}

// Generated where

var SolutionKpiManagementProductWhere = struct {
	ID                whereHelper__byte
	SolutionProductID whereHelper__byte
	CreatedAt         whereHelpertime_Time
	UpdatedAt         whereHelpertime_Time
}{
	ID:                whereHelper__byte{field: "\"solution_kpi_management_products\".\"id\""},
	SolutionProductID: whereHelper__byte{field: "\"solution_kpi_management_products\".\"solution_product_id\""},
	CreatedAt:         whereHelpertime_Time{field: "\"solution_kpi_management_products\".\"created_at\""},
	UpdatedAt:         whereHelpertime_Time{field: "\"solution_kpi_management_products\".\"updated_at\""},
}

// SolutionKpiManagementProductRels is where relationship names are stored.
var SolutionKpiManagementProductRels = struct {
	SolutionProduct string
}{
	SolutionProduct: "SolutionProduct",
}

// solutionKpiManagementProductR is where relationships are stored.
type solutionKpiManagementProductR struct {
	SolutionProduct *SolutionProduct `boil:"SolutionProduct" json:"SolutionProduct" toml:"SolutionProduct" yaml:"SolutionProduct"`
}

// NewStruct creates a new relationship struct
func (*solutionKpiManagementProductR) NewStruct() *solutionKpiManagementProductR {
	return &solutionKpiManagementProductR{}
}

func (r *solutionKpiManagementProductR) GetSolutionProduct() *SolutionProduct {
	if r == nil {
		return nil
	}
	return r.SolutionProduct
}

// solutionKpiManagementProductL is where Load methods for each relationship are stored.
type solutionKpiManagementProductL struct{}

var (
	solutionKpiManagementProductAllColumns            = []string{"id", "solution_product_id", "created_at", "updated_at"}
	solutionKpiManagementProductColumnsWithoutDefault = []string{"solution_product_id"}
	solutionKpiManagementProductColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	solutionKpiManagementProductPrimaryKeyColumns     = []string{"id"}
	solutionKpiManagementProductGeneratedColumns      = []string{}
)

type (
	// SolutionKpiManagementProductSlice is an alias for a slice of pointers to SolutionKpiManagementProduct.
	// This should almost always be used instead of []SolutionKpiManagementProduct.
	SolutionKpiManagementProductSlice []*SolutionKpiManagementProduct
	// SolutionKpiManagementProductHook is the signature for custom SolutionKpiManagementProduct hook methods
	SolutionKpiManagementProductHook func(context.Context, boil.ContextExecutor, *SolutionKpiManagementProduct) error

	solutionKpiManagementProductQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	solutionKpiManagementProductType                 = reflect.TypeOf(&SolutionKpiManagementProduct{})
	solutionKpiManagementProductMapping              = queries.MakeStructMapping(solutionKpiManagementProductType)
	solutionKpiManagementProductPrimaryKeyMapping, _ = queries.BindMapping(solutionKpiManagementProductType, solutionKpiManagementProductMapping, solutionKpiManagementProductPrimaryKeyColumns)
	solutionKpiManagementProductInsertCacheMut       sync.RWMutex
	solutionKpiManagementProductInsertCache          = make(map[string]insertCache)
	solutionKpiManagementProductUpdateCacheMut       sync.RWMutex
	solutionKpiManagementProductUpdateCache          = make(map[string]updateCache)
	solutionKpiManagementProductUpsertCacheMut       sync.RWMutex
	solutionKpiManagementProductUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var solutionKpiManagementProductAfterSelectHooks []SolutionKpiManagementProductHook

var solutionKpiManagementProductBeforeInsertHooks []SolutionKpiManagementProductHook
var solutionKpiManagementProductAfterInsertHooks []SolutionKpiManagementProductHook

var solutionKpiManagementProductBeforeUpdateHooks []SolutionKpiManagementProductHook
var solutionKpiManagementProductAfterUpdateHooks []SolutionKpiManagementProductHook

var solutionKpiManagementProductBeforeDeleteHooks []SolutionKpiManagementProductHook
var solutionKpiManagementProductAfterDeleteHooks []SolutionKpiManagementProductHook

var solutionKpiManagementProductBeforeUpsertHooks []SolutionKpiManagementProductHook
var solutionKpiManagementProductAfterUpsertHooks []SolutionKpiManagementProductHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SolutionKpiManagementProduct) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SolutionKpiManagementProduct) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SolutionKpiManagementProduct) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SolutionKpiManagementProduct) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SolutionKpiManagementProduct) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SolutionKpiManagementProduct) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SolutionKpiManagementProduct) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SolutionKpiManagementProduct) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SolutionKpiManagementProduct) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range solutionKpiManagementProductAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSolutionKpiManagementProductHook registers your hook function for all future operations.
func AddSolutionKpiManagementProductHook(hookPoint boil.HookPoint, solutionKpiManagementProductHook SolutionKpiManagementProductHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		solutionKpiManagementProductAfterSelectHooks = append(solutionKpiManagementProductAfterSelectHooks, solutionKpiManagementProductHook)
	case boil.BeforeInsertHook:
		solutionKpiManagementProductBeforeInsertHooks = append(solutionKpiManagementProductBeforeInsertHooks, solutionKpiManagementProductHook)
	case boil.AfterInsertHook:
		solutionKpiManagementProductAfterInsertHooks = append(solutionKpiManagementProductAfterInsertHooks, solutionKpiManagementProductHook)
	case boil.BeforeUpdateHook:
		solutionKpiManagementProductBeforeUpdateHooks = append(solutionKpiManagementProductBeforeUpdateHooks, solutionKpiManagementProductHook)
	case boil.AfterUpdateHook:
		solutionKpiManagementProductAfterUpdateHooks = append(solutionKpiManagementProductAfterUpdateHooks, solutionKpiManagementProductHook)
	case boil.BeforeDeleteHook:
		solutionKpiManagementProductBeforeDeleteHooks = append(solutionKpiManagementProductBeforeDeleteHooks, solutionKpiManagementProductHook)
	case boil.AfterDeleteHook:
		solutionKpiManagementProductAfterDeleteHooks = append(solutionKpiManagementProductAfterDeleteHooks, solutionKpiManagementProductHook)
	case boil.BeforeUpsertHook:
		solutionKpiManagementProductBeforeUpsertHooks = append(solutionKpiManagementProductBeforeUpsertHooks, solutionKpiManagementProductHook)
	case boil.AfterUpsertHook:
		solutionKpiManagementProductAfterUpsertHooks = append(solutionKpiManagementProductAfterUpsertHooks, solutionKpiManagementProductHook)
	}
}

// One returns a single solutionKpiManagementProduct record from the query.
func (q solutionKpiManagementProductQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SolutionKpiManagementProduct, error) {
	o := &SolutionKpiManagementProduct{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: failed to execute a one query for solution_kpi_management_products")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SolutionKpiManagementProduct records from the query.
func (q solutionKpiManagementProductQuery) All(ctx context.Context, exec boil.ContextExecutor) (SolutionKpiManagementProductSlice, error) {
	var o []*SolutionKpiManagementProduct

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler: failed to assign all query results to SolutionKpiManagementProduct slice")
	}

	if len(solutionKpiManagementProductAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SolutionKpiManagementProduct records in the query.
func (q solutionKpiManagementProductQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to count solution_kpi_management_products rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q solutionKpiManagementProductQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler: failed to check if solution_kpi_management_products exists")
	}

	return count > 0, nil
}

// SolutionProduct pointed to by the foreign key.
func (o *SolutionKpiManagementProduct) SolutionProduct(mods ...qm.QueryMod) solutionProductQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SolutionProductID),
	}

	queryMods = append(queryMods, mods...)

	return SolutionProducts(queryMods...)
}

// LoadSolutionProduct allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (solutionKpiManagementProductL) LoadSolutionProduct(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSolutionKpiManagementProduct interface{}, mods queries.Applicator) error {
	var slice []*SolutionKpiManagementProduct
	var object *SolutionKpiManagementProduct

	if singular {
		var ok bool
		object, ok = maybeSolutionKpiManagementProduct.(*SolutionKpiManagementProduct)
		if !ok {
			object = new(SolutionKpiManagementProduct)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSolutionKpiManagementProduct)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSolutionKpiManagementProduct))
			}
		}
	} else {
		s, ok := maybeSolutionKpiManagementProduct.(*[]*SolutionKpiManagementProduct)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSolutionKpiManagementProduct)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSolutionKpiManagementProduct))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &solutionKpiManagementProductR{}
		}
		if !queries.IsNil(object.SolutionProductID) {
			args = append(args, object.SolutionProductID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &solutionKpiManagementProductR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.SolutionProductID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.SolutionProductID) {
				args = append(args, obj.SolutionProductID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`solution_products`),
		qm.WhereIn(`solution_products.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SolutionProduct")
	}

	var resultSlice []*SolutionProduct
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SolutionProduct")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for solution_products")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for solution_products")
	}

	if len(solutionProductAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SolutionProduct = foreign
		if foreign.R == nil {
			foreign.R = &solutionProductR{}
		}
		foreign.R.SolutionKpiManagementProduct = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.SolutionProductID, foreign.ID) {
				local.R.SolutionProduct = foreign
				if foreign.R == nil {
					foreign.R = &solutionProductR{}
				}
				foreign.R.SolutionKpiManagementProduct = local
				break
			}
		}
	}

	return nil
}

// SetSolutionProduct of the solutionKpiManagementProduct to the related item.
// Sets o.R.SolutionProduct to related.
// Adds o to related.R.SolutionKpiManagementProduct.
func (o *SolutionKpiManagementProduct) SetSolutionProduct(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SolutionProduct) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"solution_kpi_management_products\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"solution_product_id"}),
		strmangle.WhereClause("\"", "\"", 2, solutionKpiManagementProductPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.SolutionProductID, related.ID)
	if o.R == nil {
		o.R = &solutionKpiManagementProductR{
			SolutionProduct: related,
		}
	} else {
		o.R.SolutionProduct = related
	}

	if related.R == nil {
		related.R = &solutionProductR{
			SolutionKpiManagementProduct: o,
		}
	} else {
		related.R.SolutionKpiManagementProduct = o
	}

	return nil
}

// SolutionKpiManagementProducts retrieves all the records using an executor.
func SolutionKpiManagementProducts(mods ...qm.QueryMod) solutionKpiManagementProductQuery {
	mods = append(mods, qm.From("\"solution_kpi_management_products\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"solution_kpi_management_products\".*"})
	}

	return solutionKpiManagementProductQuery{q}
}

// FindSolutionKpiManagementProduct retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSolutionKpiManagementProduct(ctx context.Context, exec boil.ContextExecutor, iD []byte, selectCols ...string) (*SolutionKpiManagementProduct, error) {
	solutionKpiManagementProductObj := &SolutionKpiManagementProduct{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"solution_kpi_management_products\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, solutionKpiManagementProductObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler: unable to select from solution_kpi_management_products")
	}

	if err = solutionKpiManagementProductObj.doAfterSelectHooks(ctx, exec); err != nil {
		return solutionKpiManagementProductObj, err
	}

	return solutionKpiManagementProductObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SolutionKpiManagementProduct) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no solution_kpi_management_products provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(solutionKpiManagementProductColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	solutionKpiManagementProductInsertCacheMut.RLock()
	cache, cached := solutionKpiManagementProductInsertCache[key]
	solutionKpiManagementProductInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			solutionKpiManagementProductAllColumns,
			solutionKpiManagementProductColumnsWithDefault,
			solutionKpiManagementProductColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(solutionKpiManagementProductType, solutionKpiManagementProductMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(solutionKpiManagementProductType, solutionKpiManagementProductMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"solution_kpi_management_products\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"solution_kpi_management_products\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "boiler: unable to insert into solution_kpi_management_products")
	}

	if !cached {
		solutionKpiManagementProductInsertCacheMut.Lock()
		solutionKpiManagementProductInsertCache[key] = cache
		solutionKpiManagementProductInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SolutionKpiManagementProduct.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SolutionKpiManagementProduct) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	solutionKpiManagementProductUpdateCacheMut.RLock()
	cache, cached := solutionKpiManagementProductUpdateCache[key]
	solutionKpiManagementProductUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			solutionKpiManagementProductAllColumns,
			solutionKpiManagementProductPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler: unable to update solution_kpi_management_products, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"solution_kpi_management_products\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, solutionKpiManagementProductPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(solutionKpiManagementProductType, solutionKpiManagementProductMapping, append(wl, solutionKpiManagementProductPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update solution_kpi_management_products row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by update for solution_kpi_management_products")
	}

	if !cached {
		solutionKpiManagementProductUpdateCacheMut.Lock()
		solutionKpiManagementProductUpdateCache[key] = cache
		solutionKpiManagementProductUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q solutionKpiManagementProductQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all for solution_kpi_management_products")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected for solution_kpi_management_products")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SolutionKpiManagementProductSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), solutionKpiManagementProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"solution_kpi_management_products\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, solutionKpiManagementProductPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to update all in solutionKpiManagementProduct slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to retrieve rows affected all in update all solutionKpiManagementProduct")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SolutionKpiManagementProduct) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("boiler: no solution_kpi_management_products provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(solutionKpiManagementProductColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	solutionKpiManagementProductUpsertCacheMut.RLock()
	cache, cached := solutionKpiManagementProductUpsertCache[key]
	solutionKpiManagementProductUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			solutionKpiManagementProductAllColumns,
			solutionKpiManagementProductColumnsWithDefault,
			solutionKpiManagementProductColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			solutionKpiManagementProductAllColumns,
			solutionKpiManagementProductPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("boiler: unable to upsert solution_kpi_management_products, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(solutionKpiManagementProductPrimaryKeyColumns))
			copy(conflict, solutionKpiManagementProductPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"solution_kpi_management_products\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(solutionKpiManagementProductType, solutionKpiManagementProductMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(solutionKpiManagementProductType, solutionKpiManagementProductMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "boiler: unable to upsert solution_kpi_management_products")
	}

	if !cached {
		solutionKpiManagementProductUpsertCacheMut.Lock()
		solutionKpiManagementProductUpsertCache[key] = cache
		solutionKpiManagementProductUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SolutionKpiManagementProduct record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SolutionKpiManagementProduct) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler: no SolutionKpiManagementProduct provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), solutionKpiManagementProductPrimaryKeyMapping)
	sql := "DELETE FROM \"solution_kpi_management_products\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete from solution_kpi_management_products")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by delete for solution_kpi_management_products")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q solutionKpiManagementProductQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler: no solutionKpiManagementProductQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from solution_kpi_management_products")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for solution_kpi_management_products")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SolutionKpiManagementProductSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(solutionKpiManagementProductBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), solutionKpiManagementProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"solution_kpi_management_products\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, solutionKpiManagementProductPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler: unable to delete all from solutionKpiManagementProduct slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler: failed to get rows affected by deleteall for solution_kpi_management_products")
	}

	if len(solutionKpiManagementProductAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SolutionKpiManagementProduct) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSolutionKpiManagementProduct(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SolutionKpiManagementProductSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SolutionKpiManagementProductSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), solutionKpiManagementProductPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"solution_kpi_management_products\".* FROM \"solution_kpi_management_products\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, solutionKpiManagementProductPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler: unable to reload all in SolutionKpiManagementProductSlice")
	}

	*o = slice

	return nil
}

// SolutionKpiManagementProductExists checks if the SolutionKpiManagementProduct row exists.
func SolutionKpiManagementProductExists(ctx context.Context, exec boil.ContextExecutor, iD []byte) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"solution_kpi_management_products\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler: unable to check if solution_kpi_management_products exists")
	}

	return exists, nil
}

// Exists checks if the SolutionKpiManagementProduct row exists.
func (o *SolutionKpiManagementProduct) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SolutionKpiManagementProductExists(ctx, exec, o.ID)
}
