// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package models

import (
	"time"
)

// CommonProperties defines model for CommonProperties.
type CommonProperties struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *[]byte    `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Company defines model for Company.
type Company struct {
	CreatedAt          *time.Time `json:"created_at,omitempty"`
	IconImgUrl         *string    `json:"icon_img_url,omitempty"`
	Id                 *[]byte    `json:"id,omitempty"`
	Name               string     `json:"name"`
	RepresentativeName *string    `json:"representative_name,omitempty"`
	Status             *string    `json:"status,omitempty"`
	UpdatedAt          *time.Time `json:"updated_at,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// NewCompany defines model for NewCompany.
type NewCompany struct {
	IconImgUrl         *string `json:"icon_img_url,omitempty"`
	Name               string  `json:"name"`
	RepresentativeName *string `json:"representative_name,omitempty"`
	Status             *string `json:"status,omitempty"`
}

// Playground defines model for Playground.
type Playground struct {
	Message string `json:"message"`
}

// PostGraphqlJSONBody defines parameters for PostGraphql.
type PostGraphqlJSONBody struct {
	// Query GraphQL query
	Query *string `json:"query,omitempty"`

	// Variables Variables for the query (if any)
	Variables *map[string]interface{} `json:"variables,omitempty"`
}

// AddCompanyJSONRequestBody defines body for AddCompany for application/json ContentType.
type AddCompanyJSONRequestBody = NewCompany

// PostGraphqlJSONRequestBody defines body for PostGraphql for application/json ContentType.
type PostGraphqlJSONRequestBody PostGraphqlJSONBody
