// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package models

import (
	"time"
)

// Comment defines model for Comment.
type Comment struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Text      string     `json:"text"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// CommonProperties defines model for CommonProperties.
type CommonProperties struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// NewComment defines model for NewComment.
type NewComment struct {
	Text string `json:"text"`
}

// PostGraphqlJSONBody defines parameters for PostGraphql.
type PostGraphqlJSONBody struct {
	// Query GraphQL query
	Query *string `json:"query,omitempty"`

	// Variables Variables for the query (if any)
	Variables *map[string]interface{} `json:"variables,omitempty"`
}

// AddCommentJSONRequestBody defines body for AddComment for application/json ContentType.
type AddCommentJSONRequestBody = NewComment

// PostGraphqlJSONRequestBody defines body for PostGraphql for application/json ContentType.
type PostGraphqlJSONRequestBody PostGraphqlJSONBody
